services:
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    env_file:
      - .env
    command: ["node", "build/db/migrateProd.js"]
    restart: "no"
    volumes:
      - data:/prod/data
    networks:
      - main

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    restart: always
    env_file:
      - .env
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - data:/prod/data
    networks:
      - main

  frontend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
      args:
        BACKEND_PORT: ${BACKEND_PORT}
        FRONTEND_PORT: ${FRONTEND_PORT}
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    restart: always

    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - main

volumes:
  data:
    name: sklad-data

networks:
  main:
    name: sklad