FROM node:24-alpine AS builder
WORKDIR /app
ENV CI=true

# install pnpm
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

# fetch packages
COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./
RUN pnpm fetch --prod

# install dependencies
COPY backend/package.json ./backend/
RUN pnpm -r install --prod --offline --frozen-lockfile 

# move configs
COPY tsconfig.json ./
COPY backend/tsconfig.json backend/tsconfig.build.json ./backend/

# build
COPY backend/src ./backend/src
COPY backend/scripts ./backend/scripts
RUN npm run back:build

CMD [ "pnpm",  "back:prod"]