export enum ErrorMessages {
  BACKEND_PORT_NOT_SET = "BACKEND_PORT is not set",
  NO_SQLITE_PATH_IN_ENV = "No sqlite path string in env",
  NO_BACKUPS_PATH_IN_ENV = "No backups path string in env",
  NO_DB_CONNECTION = "Database connection was not established",
  ITEM_NOT_FOUND = "Item was not found",
  ITEM_TO_DELETE_NOT_FOUND = "Item to delete was not found",
  ITEM_DELETED = "Item is deleted",
  NAME_ALREADY_EXISTS = "Name already exists",
  DB_OPERATION_FAILED = "Db operation failed",
  UNIT_CHANGE_AFTER_USAGE = "Unit cannot be changed after historical usage",
  VARIANT_CHANGE_AFTER_USAGE = "Material variant cannot be changed after the supply was consumed",
  INVALID_DECIMAL_VALUE = "Value is not a valid decimal number",
  INVALID_DECIMAL_PRECISION = "Value has more decimal places than allowed",
  QUANTITY_NOT_POSITIVE = "Quantity must be greater than zero",
  PRICE_NEGATIVE = "Price cannot be negative",
  QUANTITY_BELOW_CONSUMED = "Quantity cannot be lower than the already consumed amount",
  QUANTITY_REQUIRED_FOR_UNIT_CHANGE = "Quantity is required when moving a supply to a variant with a different unit",
  REFERENCED_ITEM_DELETED = "Referenced record is deleted",
  INVALID_REQUEST = "Invalid request",
  RESOURCE_NOT_FOUND = "Resource not found",
  CONFLICT = "Conflict with existing data",
  INTERNAL_SERVER_ERROR = "Internal server error",
  OPENAPI_NOT_FOUND = "OpenAPI spec not found",
}
